version: "3.8"

networks:
  default:
    driver: bridge

services:
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default

  app:
    build: .
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s /start.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - default
